/**
 * This file was automatically generated by generate-json-schema-to-ts.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source file JSON file: vitest-runner-options.json,
 * and run 'npm run generate' from monorepo base directory.
 */
export interface StrykerVitestRunnerOptions {
    vitest: VitestRunnerOptions;
}
/**
 * Configuration for @stryker-mutator/vitest-runner
 */
export interface VitestRunnerOptions {
    /**
     * Configure the `--dir <path>` command line option
     */
    dir?: string;
    /**
     * Use [related mode](https://vitest.dev/guide/cli.html#vitest-related) to narrow down the tests to run
     */
    related: boolean;
    /**
     * Path to the config file. Default resolving to `vitest.config.*`, `vite.config.*`
     */
    configFile?: string;
}
//# sourceMappingURL=vitest-runner-options.d.ts.map