/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PtySessionInfo } from './pty-session-info';
export interface PtyListResponse {
    /**
     * List of active PTY sessions
     */
    'sessions': Array<PtySessionInfo>;
}
