/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { InitializeRequest } from '../models';
/**
 * ServerApi - axios parameter creator
 */
export declare const ServerApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     * Set the auth token and initialize telemetry for the toolbox server
     * @summary Initialize toolbox server
     * @param {InitializeRequest} request Initialization request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initialize: (request: InitializeRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * ServerApi - functional programming interface
 */
export declare const ServerApiFp: (configuration?: Configuration) => {
    /**
     * Set the auth token and initialize telemetry for the toolbox server
     * @summary Initialize toolbox server
     * @param {InitializeRequest} request Initialization request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initialize(request: InitializeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{
        [key: string]: string;
    }>>;
};
/**
 * ServerApi - factory interface
 */
export declare const ServerApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     * Set the auth token and initialize telemetry for the toolbox server
     * @summary Initialize toolbox server
     * @param {InitializeRequest} request Initialization request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initialize(request: InitializeRequest, options?: RawAxiosRequestConfig): AxiosPromise<{
        [key: string]: string;
    }>;
};
/**
 * ServerApi - object-oriented interface
 */
export declare class ServerApi extends BaseAPI {
    /**
     * Set the auth token and initialize telemetry for the toolbox server
     * @summary Initialize toolbox server
     * @param {InitializeRequest} request Initialization request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    initialize(request: InitializeRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<{
        [key: string]: string;
    }, any, {}>>;
}
