"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ComputerUseStatusResponseStatusEnum = void 0;
exports.ComputerUseStatusResponseStatusEnum = {
    ACTIVE: 'active',
    PARTIAL: 'partial',
    INACTIVE: 'inactive',
    ERROR: 'error',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
};
//# sourceMappingURL=computer-use-status-response.js.map