/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { PaginatedAuditLogs } from '../models';
/**
 * AuditApi - axios parameter creator
 */
export declare const AuditApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Get audit logs for organization
     * @param {string} organizationId Organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {Date} [from] From date (ISO 8601 format)
     * @param {Date} [to] To date (ISO 8601 format)
     * @param {string} [nextToken] Token for cursor-based pagination. When provided, takes precedence over page parameter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationAuditLogs: (organizationId: string, page?: number, limit?: number, from?: Date, to?: Date, nextToken?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AuditApi - functional programming interface
 */
export declare const AuditApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Get audit logs for organization
     * @param {string} organizationId Organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {Date} [from] From date (ISO 8601 format)
     * @param {Date} [to] To date (ISO 8601 format)
     * @param {string} [nextToken] Token for cursor-based pagination. When provided, takes precedence over page parameter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationAuditLogs(organizationId: string, page?: number, limit?: number, from?: Date, to?: Date, nextToken?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedAuditLogs>>;
};
/**
 * AuditApi - factory interface
 */
export declare const AuditApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Get audit logs for organization
     * @param {string} organizationId Organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {Date} [from] From date (ISO 8601 format)
     * @param {Date} [to] To date (ISO 8601 format)
     * @param {string} [nextToken] Token for cursor-based pagination. When provided, takes precedence over page parameter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationAuditLogs(organizationId: string, page?: number, limit?: number, from?: Date, to?: Date, nextToken?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedAuditLogs>;
};
/**
 * AuditApi - object-oriented interface
 */
export declare class AuditApi extends BaseAPI {
    /**
     *
     * @summary Get audit logs for organization
     * @param {string} organizationId Organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {Date} [from] From date (ISO 8601 format)
     * @param {Date} [to] To date (ISO 8601 format)
     * @param {string} [nextToken] Token for cursor-based pagination. When provided, takes precedence over page parameter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationAuditLogs(organizationId: string, page?: number, limit?: number, from?: Date, to?: Date, nextToken?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PaginatedAuditLogs, any, {}>>;
}
