"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Status = void 0;
exports.Status = {
    Unmodified: 'Unmodified',
    Untracked: 'Untracked',
    Modified: 'Modified',
    Added: 'Added',
    Deleted: 'Deleted',
    Renamed: 'Renamed',
    Copied: 'Copied',
    UpdatedButUnmerged: 'Updated but unmerged',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
};
//# sourceMappingURL=status.js.map