/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare const Status: {
    readonly Unmodified: "Unmodified";
    readonly Untracked: "Untracked";
    readonly Modified: "Modified";
    readonly Added: "Added";
    readonly Deleted: "Deleted";
    readonly Renamed: "Renamed";
    readonly Copied: "Copied";
    readonly UpdatedButUnmerged: "Updated but unmerged";
    readonly UNKNOWN_DEFAULT_OPEN_API: "11184809";
};
export type Status = typeof Status[keyof typeof Status];
