/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { FileInfo } from '../models';
import type { FilesDownloadRequest } from '../models';
import type { Match } from '../models';
import type { ReplaceRequest } from '../models';
import type { ReplaceResult } from '../models';
import type { SearchFilesResponse } from '../models';
/**
 * FileSystemApi - axios parameter creator
 */
export declare const FileSystemApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     * Create a folder with the specified path and optional permissions
     * @summary Create a folder
     * @param {string} path Folder path to create
     * @param {string} mode Octal permission mode (default: 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createFolder: (path: string, mode: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Delete a file or directory at the specified path
     * @summary Delete a file or directory
     * @param {string} path File or directory path to delete
     * @param {boolean} [recursive] Enable recursive deletion for directories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteFile: (path: string, recursive?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Download a file by providing its path
     * @summary Download a file
     * @param {string} path File path to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFile: (path: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Download multiple files by providing their paths. Successful files are returned as multipart parts named `file`. Per-file failures are returned as multipart parts named `error` with JSON payloads shaped like ErrorResponse.
     * @summary Download multiple files
     * @param {FilesDownloadRequest} downloadFiles Paths of files to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFiles: (downloadFiles: FilesDownloadRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Search for text pattern within files in a directory
     * @summary Find text in files
     * @param {string} path Directory path to search in
     * @param {string} pattern Text pattern to search for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findInFiles: (path: string, pattern: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Get detailed information about a file or directory
     * @summary Get file information
     * @param {string} path File or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileInfo: (path: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * List files and directories in the specified path
     * @summary List files and directories
     * @param {string} [path] Directory path to list (defaults to working directory)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listFiles: (path?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Move or rename a file or directory from source to destination
     * @summary Move or rename file/directory
     * @param {string} source Source file or directory path
     * @param {string} destination Destination file or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    moveFile: (source: string, destination: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Replace text pattern with new value in multiple files
     * @summary Replace text in files
     * @param {ReplaceRequest} request Replace request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceInFiles: (request: ReplaceRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Search for files matching a specific pattern in a directory
     * @summary Search files by pattern
     * @param {string} path Directory path to search in
     * @param {string} pattern File pattern to match (e.g., *.txt, *.go)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchFiles: (path: string, pattern: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Set file permissions, ownership, and group for a file or directory
     * @summary Set file permissions
     * @param {string} path File or directory path
     * @param {string} [owner] Owner (username or UID)
     * @param {string} [group] Group (group name or GID)
     * @param {string} [mode] File mode in octal format (e.g., 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setFilePermissions: (path: string, owner?: string, group?: string, mode?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Upload a file to the specified path
     * @summary Upload a file
     * @param {string} path Destination path for the uploaded file
     * @param {File} file File to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFile: (path: string, file: File, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Upload multiple files with their destination paths
     * @summary Upload multiple files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFiles: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * FileSystemApi - functional programming interface
 */
export declare const FileSystemApiFp: (configuration?: Configuration) => {
    /**
     * Create a folder with the specified path and optional permissions
     * @summary Create a folder
     * @param {string} path Folder path to create
     * @param {string} mode Octal permission mode (default: 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createFolder(path: string, mode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * Delete a file or directory at the specified path
     * @summary Delete a file or directory
     * @param {string} path File or directory path to delete
     * @param {boolean} [recursive] Enable recursive deletion for directories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteFile(path: string, recursive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * Download a file by providing its path
     * @summary Download a file
     * @param {string} path File path to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFile(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>>;
    /**
     * Download multiple files by providing their paths. Successful files are returned as multipart parts named `file`. Per-file failures are returned as multipart parts named `error` with JSON payloads shaped like ErrorResponse.
     * @summary Download multiple files
     * @param {FilesDownloadRequest} downloadFiles Paths of files to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFiles(downloadFiles: FilesDownloadRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{
        [key: string]: object;
    }>>;
    /**
     * Search for text pattern within files in a directory
     * @summary Find text in files
     * @param {string} path Directory path to search in
     * @param {string} pattern Text pattern to search for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findInFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Match>>>;
    /**
     * Get detailed information about a file or directory
     * @summary Get file information
     * @param {string} path File or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileInfo(path: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileInfo>>;
    /**
     * List files and directories in the specified path
     * @summary List files and directories
     * @param {string} [path] Directory path to list (defaults to working directory)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listFiles(path?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FileInfo>>>;
    /**
     * Move or rename a file or directory from source to destination
     * @summary Move or rename file/directory
     * @param {string} source Source file or directory path
     * @param {string} destination Destination file or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    moveFile(source: string, destination: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * Replace text pattern with new value in multiple files
     * @summary Replace text in files
     * @param {ReplaceRequest} request Replace request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceInFiles(request: ReplaceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReplaceResult>>>;
    /**
     * Search for files matching a specific pattern in a directory
     * @summary Search files by pattern
     * @param {string} path Directory path to search in
     * @param {string} pattern File pattern to match (e.g., *.txt, *.go)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchFilesResponse>>;
    /**
     * Set file permissions, ownership, and group for a file or directory
     * @summary Set file permissions
     * @param {string} path File or directory path
     * @param {string} [owner] Owner (username or UID)
     * @param {string} [group] Group (group name or GID)
     * @param {string} [mode] File mode in octal format (e.g., 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setFilePermissions(path: string, owner?: string, group?: string, mode?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * Upload a file to the specified path
     * @summary Upload a file
     * @param {string} path Destination path for the uploaded file
     * @param {File} file File to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFile(path: string, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{
        [key: string]: object;
    }>>;
    /**
     * Upload multiple files with their destination paths
     * @summary Upload multiple files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFiles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * FileSystemApi - factory interface
 */
export declare const FileSystemApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     * Create a folder with the specified path and optional permissions
     * @summary Create a folder
     * @param {string} path Folder path to create
     * @param {string} mode Octal permission mode (default: 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createFolder(path: string, mode: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     * Delete a file or directory at the specified path
     * @summary Delete a file or directory
     * @param {string} path File or directory path to delete
     * @param {boolean} [recursive] Enable recursive deletion for directories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteFile(path: string, recursive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     * Download a file by providing its path
     * @summary Download a file
     * @param {string} path File path to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFile(path: string, options?: RawAxiosRequestConfig): AxiosPromise<File>;
    /**
     * Download multiple files by providing their paths. Successful files are returned as multipart parts named `file`. Per-file failures are returned as multipart parts named `error` with JSON payloads shaped like ErrorResponse.
     * @summary Download multiple files
     * @param {FilesDownloadRequest} downloadFiles Paths of files to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFiles(downloadFiles: FilesDownloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<{
        [key: string]: object;
    }>;
    /**
     * Search for text pattern within files in a directory
     * @summary Find text in files
     * @param {string} path Directory path to search in
     * @param {string} pattern Text pattern to search for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findInFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Match>>;
    /**
     * Get detailed information about a file or directory
     * @summary Get file information
     * @param {string} path File or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileInfo(path: string, options?: RawAxiosRequestConfig): AxiosPromise<FileInfo>;
    /**
     * List files and directories in the specified path
     * @summary List files and directories
     * @param {string} [path] Directory path to list (defaults to working directory)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listFiles(path?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<FileInfo>>;
    /**
     * Move or rename a file or directory from source to destination
     * @summary Move or rename file/directory
     * @param {string} source Source file or directory path
     * @param {string} destination Destination file or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    moveFile(source: string, destination: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     * Replace text pattern with new value in multiple files
     * @summary Replace text in files
     * @param {ReplaceRequest} request Replace request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceInFiles(request: ReplaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ReplaceResult>>;
    /**
     * Search for files matching a specific pattern in a directory
     * @summary Search files by pattern
     * @param {string} path Directory path to search in
     * @param {string} pattern File pattern to match (e.g., *.txt, *.go)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchFilesResponse>;
    /**
     * Set file permissions, ownership, and group for a file or directory
     * @summary Set file permissions
     * @param {string} path File or directory path
     * @param {string} [owner] Owner (username or UID)
     * @param {string} [group] Group (group name or GID)
     * @param {string} [mode] File mode in octal format (e.g., 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setFilePermissions(path: string, owner?: string, group?: string, mode?: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     * Upload a file to the specified path
     * @summary Upload a file
     * @param {string} path Destination path for the uploaded file
     * @param {File} file File to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFile(path: string, file: File, options?: RawAxiosRequestConfig): AxiosPromise<{
        [key: string]: object;
    }>;
    /**
     * Upload multiple files with their destination paths
     * @summary Upload multiple files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFiles(options?: RawAxiosRequestConfig): AxiosPromise<void>;
};
/**
 * FileSystemApi - object-oriented interface
 */
export declare class FileSystemApi extends BaseAPI {
    /**
     * Create a folder with the specified path and optional permissions
     * @summary Create a folder
     * @param {string} path Folder path to create
     * @param {string} mode Octal permission mode (default: 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createFolder(path: string, mode: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     * Delete a file or directory at the specified path
     * @summary Delete a file or directory
     * @param {string} path File or directory path to delete
     * @param {boolean} [recursive] Enable recursive deletion for directories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteFile(path: string, recursive?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     * Download a file by providing its path
     * @summary Download a file
     * @param {string} path File path to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFile(path: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<File, any, {}>>;
    /**
     * Download multiple files by providing their paths. Successful files are returned as multipart parts named `file`. Per-file failures are returned as multipart parts named `error` with JSON payloads shaped like ErrorResponse.
     * @summary Download multiple files
     * @param {FilesDownloadRequest} downloadFiles Paths of files to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadFiles(downloadFiles: FilesDownloadRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<{
        [key: string]: object;
    }, any, {}>>;
    /**
     * Search for text pattern within files in a directory
     * @summary Find text in files
     * @param {string} path Directory path to search in
     * @param {string} pattern Text pattern to search for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findInFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Match[], any, {}>>;
    /**
     * Get detailed information about a file or directory
     * @summary Get file information
     * @param {string} path File or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileInfo(path: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<FileInfo, any, {}>>;
    /**
     * List files and directories in the specified path
     * @summary List files and directories
     * @param {string} [path] Directory path to list (defaults to working directory)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listFiles(path?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<FileInfo[], any, {}>>;
    /**
     * Move or rename a file or directory from source to destination
     * @summary Move or rename file/directory
     * @param {string} source Source file or directory path
     * @param {string} destination Destination file or directory path
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    moveFile(source: string, destination: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     * Replace text pattern with new value in multiple files
     * @summary Replace text in files
     * @param {ReplaceRequest} request Replace request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replaceInFiles(request: ReplaceRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ReplaceResult[], any, {}>>;
    /**
     * Search for files matching a specific pattern in a directory
     * @summary Search files by pattern
     * @param {string} path Directory path to search in
     * @param {string} pattern File pattern to match (e.g., *.txt, *.go)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchFiles(path: string, pattern: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<SearchFilesResponse, any, {}>>;
    /**
     * Set file permissions, ownership, and group for a file or directory
     * @summary Set file permissions
     * @param {string} path File or directory path
     * @param {string} [owner] Owner (username or UID)
     * @param {string} [group] Group (group name or GID)
     * @param {string} [mode] File mode in octal format (e.g., 0755)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setFilePermissions(path: string, owner?: string, group?: string, mode?: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     * Upload a file to the specified path
     * @summary Upload a file
     * @param {string} path Destination path for the uploaded file
     * @param {File} file File to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFile(path: string, file: File, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<{
        [key: string]: object;
    }, any, {}>>;
    /**
     * Upload multiple files with their destination paths
     * @summary Upload multiple files
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadFiles(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
}
